clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

when:
  - event: push
    branch: main

steps:
  - name: lint
    image: golangci/golangci-lint:v2.10
    commands:
      - golangci-lint run --timeout=5m ./...

  - name: test
    image: golang:1.26
    commands:
      - go test -v -count=1 ./...
