clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

when:
  - event: push
    branch: main

steps:
  - name: test
    image: golang:1.26
    commands:
      - go test -v -count=1 ./...
