clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      partial: false
      depth: 0

when:
  - event: pull_request

steps:
  - name: lint
    image: golangci/golangci-lint:v2.11.4
    commands:
      - golangci-lint run ./...

  - name: test
    image: golang:1.26
    commands:
      - go test -v -count=1 ./...
